spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master,如果你主从默认下主库的名称就是master可不定义此项。
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://148.70.213.66:3306/vue-fast?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          username: root
          password: Root1234!
          initial-size: 10
          max-active: 100
          min-idle: 10
#        slaver1:
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://148.70.213.66:3306/vue-fast?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#          username: root
#          password: Root1234!
#          initial-size: 10
#          max-active: 100
#          min-idle: 10