
server:
  port: 8989
spring:
  application:
    name: yd-flowable
  # 环境 dev|test|prod
  profiles:
    active: dev
  security:
    filter:
      dispatcher-types: REQUEST,FORWARD,ASYNC
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true


logging:
  level:
    org.flowable.engine.impl.persistence.entity: debug
    org.flowable.idm.impl.persistence.entity: debug




